### PR TITLE
iOS 9 support

### PR DESCRIPTION
**Pull request by joemerlino**
Don't merge the README.md because I changed the contacts and donations link.

Just imported the needed UIKit.h and framework.

### CODE REVIEW

**Comment by singhofmarco** [comment]
Thanks for your help. Will merge. Had serious problems with theos on my mac.

**Comment by joemerlino** [comment]
@singhofmarco wait, I need to test it with my 64bit iPad, no problem with 32bit but just to be safe before merging.

**Comment by singhofmarco** [comment]
Yeah I guess you missed the new compile flag!

**Comment by joemerlino** [comment]
I think you're right lol

**Comment by singhofmarco** [comment]
I won't merge it, 'cause then there wouldn't be support for iOS 7-8. But I will use your code. Thanks!

**Comment by joemerlino** [comment]
Yea you should make 2 groups based on firmware but I didn't have time haha. 

Thank you for the original tweak!

**Comment by singhofmarco** [comment]
No problem. You already helped me! :+1: 
I will do this..

Again no problem

**Comment by singhofmarco** [comment]
Do you have Twitter?

**Comment by joemerlino** [comment]
[Yup](http://twitter.com/joe_merlino) :)

**Comment by singhofmarco** [comment]
Where do you have your headers from? I'm constantly getting errors

**Comment by singhofmarco** [comment]
Problem solved

**Pull request closed without merging**
